### ISSUE TITLE
CoreEngine Windows Messages

### ISSUE THREAD

**Issue by gortega56** [igm-grad/GGPEngine#1]
The starter code that was imported from DirectX Starter that handles Windows messages should be moved into CoreEngine. The CoreEngine should receive Windows messages and forward them appropriately. 

For example, if the window becomes inactive the CoreEngine timer should pause any rendering or physics simulation.

@tiagomartines11 did we decide to have the CoreEngine respond to the resize message as well?

**Comment by tiagomartines11** [comment]
We decided that CoreEngine would deal with all Windows messages, simply because some are useful for general stuff (e.g. timers). That means it will need to handle resizing, but that can be a simple call to the RenderEngine resize method.

**Comment by tiagomartines11** [comment]
So we need to move code around ;)

**Comment by gortega56** [comment]
@tiagomartines11 this is all done right?
