### ISSUE TITLE
GameObject API

### ISSUE THREAD

**Issue by gortega56** [igm-grad/GGPEngine#27]
There are methods stubs that still need to be filled out in the GameObject class. These methods mostly have to to with movement such as:

void applyRotation(XMFLOAT3X3 rotation);
void rotateHeading(float angle);
void rotatePitch(float angle);
void rotateYaw(float angle);

**Comment by tiagomartines11** [comment]
Alternative: create a Transform class for those functions/attributes. Re-usable between Camera and GameObject.
