### ISSUE TITLE
PhysicsEngine: RigidBody Class

### ISSUE THREAD

**Issue by gortega56** [igm-grad/GGPEngine#3]
The PhysicsEngine will require a RigidBody Class to perform integration. The RigidBody class requires the following members:

Vector3 acceleration,
Vector3 velocity,
float mass,
float inverseMass

-- more I can't think of right now.

**Comment by gortega56** [comment]
Vector3 angularVelocity
Vector3 momentum
Vector3 angularMomentum
Quaternion spin?

use this as template:

http://gafferongames.com/game-physics/physics-in-3d/

**Comment by Meith** [comment]
Got this.
